[package]
name = "emoji-test"
version = "0.1.0"
authors = ["Tom Pridham <pridham.tom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
imageproc = "0.21.0"
rusttype = "0.9.2"
